### ISSUE TITLE
Document conversion gotchas

### ISSUE THREAD

**Issue by TrevorBurnham** [js2coffee/js2coffee#1]
Whenever folks asked me in the past why there wasn't a JS-to-CoffeeScript converter, my go-to answer was: "Well, what about `==`? CoffeeScript doesn't have an equivalent. It only has `===`. And what about scope? You can't have two variables with the same name in two different (nested, non-global) scopes, and you can't directly modify globals."

js2coffee takes the simplest approach: `a == b` is converted straight to `a == b`, and `c = d` is converted straight to `c = d`. But these are very different statements. The first might have the same behavior in practice, but the latter definitely won't, since `c` is `window.c` or `global.c` in one language and `var c` in the other.

So at the very least, I hope you'll put mention of some of these gotchas in the README, and encourage thorough testing of converted code. You could also go a step further by adding comments to the output, e.g. when you put in

    a = b;

the output could be

    a = b  # warning: original JS may modify a global

**Comment by rstacruz** [comment]
This is now addressed by the new compatibility mode and warnings. `a == b` will produce a warning, and more consistent behavior can be achieved by turning on compatibility mode (at the expense of pretty code).
