### ISSUE TITLE
error: "env: coffee: No such file or directory" when installed to ./node_modules with npm

### ISSUE THREAD

**Issue by stepheneb** [js2coffee/js2coffee#123]
Am getting the following error:

    env: coffee: No such file or directory

I installed js2coffee@0.1.3  to ./node_modules/js2coffee by adding to devDependencies in package.json

    "devDependencies": {
      "uglify-js": "1.2.3",
      "jsdom": "0.2.10",
      "vows": "0.6.1",
      "coffee-script": "1.2.0",
      "js2coffee": "0.1.3"
    },

I got these errors trying to runjs2coffee:

    $ ./node_modules/js2coffee/bin/js2coffee src/lab/arrays/arrays.js 
    env: coffee: No such file or directory
    $ ./node_modules/js2coffee/bin/js2coffee --help
    env: coffee: No such file or directory

**Comment by rstacruz** [comment]
fixed in 2.0. no need for `apt-get install coffeescript`.
