### ISSUE TITLE
wrong conversion of  ! (e instanceof Object);

### ISSUE THREAD

**Issue by ich** [js2coffee/js2coffee#124]
It
<pre>
if (url && url != "about:blank") {
  content = getContent(url)
  content = (function(e) {
    if (! (e instanceof Object) || e instanceof Array) {
      alert("ERROOOOOOOR!");
    }
  })(content);
}
</pre>

parses into

<pre>
if url and url isnt "about:blank"
  content = getContent(url)
  content = ((e) ->
    alert "ERROOOOOOOR!"  if (e instanceof Object) or e instanceof Array
  )(content)
</pre>

but I expect this

<pre>
if url and url isnt "about:blank"
  content = getContent(url)
  content = ((e) ->
    alert "ERROOOOOOOR!"  if (e not instanceof Object) or e instanceof Array
  )(content)
</pre>

but this
<pre>
//if (url && url != "about:blank") {
  content = getContent(url)
  content = (function(e) {
    if (! (e instanceof Object) || e instanceof Array) {
      alert("ERROOOOOOOR!");
    }
  })(content);
//}
</pre>

and this 

<pre>
if (url && url != "about:blank") {
//  content = getContent(url)
//  content = (function(e) {
    if (! (e instanceof Object) || e instanceof Array) {
      alert("ERROOOOOOOR!");
    }
//  })(content);
}
</pre>

parse right.

Help plz :)

**Comment by rstacruz** [comment]
fixed in 2.0. [demo](http://js2.coffee/#try:if%20%280%29%20{%0A%20%20%28function%28%29%20{%0A%20%20%20%20!%20%28e%20instanceof%20Object%29%3B%0A%20%20}%29%3B%0A})
