### ISSUE TITLE
Regexp after try {} catch (e) {} complains about "missing operand"

### ISSUE THREAD

**Issue by xfix** [js2coffee/js2coffee#125]
If parser will see regexp after try {} catch (e) {} block, it will decide to fail. It doesn't happen if semicolon is in between.

    try {} catch (e) {}
    /regexp/

Causes following message to appear:

> SyntaxError: missing operand

**Comment by rstacruz** [comment]
works in 2.0. thanks for the report! [demo](http://js2.coffee/#try:try%20{}%20catch%20%28e%29%20{}%0A%2Fregexp%2F)
