### ISSUE TITLE
Suffix if / unless should use one space

### ISSUE THREAD

**Issue by paulmillr** [js2coffee/js2coffee#129]
I believe suffix if / unless should be separated using one space instead of two. This code style is very widely used in coffee code, Jeremy-approved [coffee style guide](https://github.com/polarmobile/coffeescript-style-guide) uses one space etc.

```
statement  unless expr
# should become:
statement unless expr
```

**Comment by rstacruz** [comment]
not revelant in 2.0 anymore.
