### ISSUE TITLE
Throw an error when shadowing is used

### ISSUE THREAD

**Issue by shesek** [js2coffee/js2coffee#140]
As CoffeeScript doesn't support shadowing, the following code has no CoffeeScript-equivalent version:

```javascript
var foo = 123;
var bar = function() { var foo = 456; }
```

This compiles to:
```coffee
foo = 123
bar = ->
  foo = 456
```

Which has a different meaning - it makes the internal `foo` assignment change the `foo` on the outer scope, rather than creating a new `foo` inside the `bar` scope as the JavaScript version does. In CoffeeScript, you have to use different variable names to make it work.

I converted some JavaScript code that expected shadowing to work, and it just broke completely... which was quite hard to debug. IMHO js2coffee should instead throw an error, or at least an warning, telling the user that the JavaScript code can't be converted properly to CoffeeScript, rather than creating code with a different meaning that might break.

**Comment by rstacruz** [comment]
it now does it 2.0. [demo](http://js2.coffee/#try:var%20foo%20%3D%20123%3B%0Avar%20bar%20%3D%20function%28%29%20{%20var%20foo%20%3D%20456%3B%20})
