### ISSUE TITLE
JS keywords and reserved words doesn't work with dot notation -> Missing identifier

### ISSUE THREAD

**Issue by uberbrady** [js2coffee/js2coffee#157]
It took me a long time to figure out why my code wouldn't convert from js to coffee.

Turns out I had a bit like this:

```js
var memcached=require('memcache');

...

memcached.delete(...);
```

I guess the delete method conflicted with the built in delete() operator?

**Comment by rstacruz** [comment]
Fixed in redux: [demo](http://js2coffee.github.io/js2coffee-redux/#try:var%20memcached%3Drequire%28%27memcache%27%29%3B%0Amemcached.delete%28foobar%29%3B)
