### ISSUE TITLE
Miniclip: a handy tool for Web developers.

### ISSUE THREAD

**Issue by myguidingstar** [js2coffee/js2coffee#170]
I've just made Miniclip, a Linux tray app that quickly converts HTML to Jade, CSS to Stylus and JS to Coffee from clipboard.
http://myguidingstar.github.com/miniclip/
and of course, it uses js2coffee

**Comment by rstacruz** [comment]
Thanks!

js2coffee 2.0.0 is out and you may want to revisit your js2coffee integration.
