### ISSUE TITLE
Error with special chars for an identifier

### ISSUE THREAD

**Issue by jamesxt** [js2coffee/js2coffee#178]
I'm from Colombia
Look this code. If I write in Js->coffee

pestañas = "";
alert(pestañas);

When I compile it

SyntaxError: Illegal token

but if I write Coffee->Js

pestañas = ""
alert pestañas

very well! No problem...

**Comment by rstacruz** [comment]
works in v2.0. [demo](http://js2.coffee/#try:pesta%C3%B1as%20%3D%20%22%22%3B%0Aalert%28pesta%C3%B1as%29%3B)
