### ISSUE TITLE
Problem with variable reordering in Js2Coffee, causing a local variable to be inserted in function thus breaking the code

### ISSUE THREAD

**Issue by gyromaxx** [js2coffee/js2coffee#181]
On Web site <http://js2coffee.org/>, the following JavaScript code:
<pre>
var world;
function Start()
{
    world = new World();
}
</pre>

... is converted to the following CoffeeScript code (with the variable moved to the end!?):
<pre>
Start = ->
  world = new World()
world = undefined
</pre>

... and converted back to JavaScript:
<pre>
var Start, world;

Start = function() {
  var world;
  return world = new World();
};

world = void 0;
</pre>

... which is not equivalent (local variable introduced into function), and the code does not run any more (outer variable remains undefined).

But in the CoffeeScript code, manually moving the variable on top seems to fix the problem:
<pre>
world = undefined
Start = ->
  world = new World()
</pre>

... converted to:
<pre>
var Start, world;

world = void 0;

Start = function() {
  return world = new World();
};
</pre>

I guess this needs to be fixed in the Js2Coffee conversion algorithm...

In any case, many thanks for this very useful tool!

**Comment by rstacruz** [comment]
Thanks for the report: this has been fixed in 2.0. Variable declarations will always be above function declarations. [demo](http://js2.coffee/#try:var%20world%3B%0Afunction%20Start%28%29%0A{%0A%20%20%20%20world%20%3D%20new%20World%28%29%3B%0A})
