### ISSUE TITLE
wrong conversion of IIFE syntax

### ISSUE THREAD

**Issue by jpillora** [js2coffee/js2coffee#190]
``` js
window.foo = (function() {
    return 42;
}());
```
converts to:
``` coffeescript
window.foo = (->
  42
())
```

end braces should be: `)()`

**Comment by rstacruz** [comment]
now gets converted to:

```coffee
window.foo = do ->
  42
```

[demo](http://js2.coffee/#try:window.foo%20%3D%20%28function%28%29%20{%0A%20%20%20%20return%2042%3B%0A}%28%29%29%3B)

**Comment by jpillora** [comment]
nice work with the new version, what's the purpose of the "preview" window? did people not like the two-way conversion?

**Comment by rstacruz** [comment]
mostly i felt it was ambiguous—you weren't sure if you were in js->coffee mode or coffee->js mode. moreso, i dont want to encourage the behavior of getting CoffeeScript output and passing it back to js2coffee :)
