### ISSUE TITLE
Compilation bug with self-invoking anonymous function

### ISSUE THREAD

**Issue by mklement0** [js2coffee/js2coffee#200]
First things first: great project, very helpful.

As of v0.2.0, when you compile this:

    var testFunc =(function(){
      var inclosure = 'in closure';
      return function() { return inclosure; };
    }());

you get this:

    testFunc = (->
      inclosure = "in closure"
      ->
        inclosure
    ()) # <- bug here: this line should read ')()'

As you can see the, the empty pair of parentheses should go OUTSIDE the parentheses enclosing the anonymous function.

**Comment by rstacruz** [comment]
IIFE's are handled with the `do ->` convention in 2.0. [demo](http://js2.coffee/#try:var%20testFunc%20%3D%28function%28%29{%0A%20%20var%20inclosure%20%3D%20%27in%20closure%27%3B%0A%20%20return%20function%28%29%20{%20return%20inclosure%3B%20}%3B%0A}%28%29%29%3B)
