### ISSUE TITLE
I put this grunt task together for js2coffee...

### ISSUE THREAD

**Issue by jonschlinkert** [js2coffee/js2coffee#202]
In case anyone can benefit from it. https://github.com/jonschlinkert/grunt-js2coffee

I mention it here because I use js2coffee a lot, and I'd love to see this maintained again. I'm happy to start taking pull requests on my repo.

**Comment by rstacruz** [comment]
Thanks! Hey! you may want to check if it's still compatible with 2.0, released just now. have a look at the migration guide in the docs.
