### ISSUE TITLE
Incorrect translation of if (false){ if (!false) {}}

### ISSUE THREAD

**Issue by sellonen** [js2coffee/js2coffee#213]
Hi, I think this block of code is translated incorrectly to coffeescript:

    if (false){
      if (!false){ console.log('hello'); }
    }

as 

    console.log "hello"  unless false  if false

which is read as 

    console.log "hello" unless (true if false)

**Comment by rstacruz** [comment]
solved in 2.0.0: [demo](http://js2.coffee/#try:if%20%28false%29{%0A%20%20if%20%28!false%29{%20console.log%28%27hello%27%29%3B%20}%0A}%0A)
