### ISSUE TITLE
Support sparse array literals

### ISSUE THREAD

**Issue by vitali2y** [js2coffee/js2coffee#217]
Hi, http://github.com/honza/140medley/blob/master/140medley.js cannot be converted producing "TypeError: Cannot set property 'is_list_element' of null", and thank you for great tool.

**Comment by rstacruz** [comment]
I'll take a stab at implementing this in redux. It will throw an error by default, but be enclosed in backticks in compatibility mode.

**Comment by flying-sheep** [comment]
`[, 0]` is not the same as `[undefined, 0], as the former is sparse:

```js
Object.keys([         , 0]) === ["1"]
Object.keys([undefined, 0]) === ["0","1"]
```

**Comment by rstacruz** [comment]
now supported in 2.0 in compatibility mode. [demo](http://js2.coffee/#try:%5B%2C0%5D), be sure to toggle "compatibility mode" on the right.

**Comment by flying-sheep** [comment]
nice!
