### ISSUE TITLE
js2coffee 0.1.3 fails to conver js files with default values in functions

### ISSUE THREAD

**Issue by mgulyaev** [js2coffee/js2coffee#232]
The following code can help to reproduce it:

```
function foo(bar = "default value") { return bar }
```

js2coffee fails to convert it

**Comment by rstacruz** [comment]
btw, on a note relevant to js2coffee-redux — even [esprima-harmony](https://www.npmjs.com/package/esprima-harmony) doesn't account for this case yet (it will parse it, but will discard the `"default value"`). looking forward to implementing it there once the feature lands in esprima-harmony.
