### ISSUE TITLE
wrong order of comments if function declaration is at the bottom

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#237]
from [Preserve comments#issuecomment-12585422](https://github.com/rstacruz/js2coffee/issues/4#issuecomment-12585422)

>
I found that comments work fairly well, but not when a function-declaration is placed last. I am using js2coffee to convert jasmine-testcases.
>
Example below, if the function "thisFunctionMessesUpWhereJs2CoffeePlacesComments" is moved to the top, all works well.

```javascript
	describe("My example testcase", function () {

		function myFunc1(s1, s2) {
			return s1 - s2;
		}

		function someOtherFunction() {
			var t = 2;
			return t;
		}

		describe("Something here", function () {
			beforeEach(function () {
				createController();
				expect(janbanan).toBe(false); // Expect Janbanan always to be false
			});

			it("should update something", function () {
				var x = 1;
				expect(x).toBe(1);  // This should work!
			});
		});


		describe("when something else happens", function () {
			beforeEach(function () {
				jumpReallyHigh();  // Needs to be a comment here
			});

			it("should not do anything", function () {
				var x = 33
				expect(x).toBe(33);
			});
		});

		function thisFunctionMessesUpWhereJs2CoffeePlacesComments(x) {
			var t = x
			return t;
		}

	});

**Comment by rstacruz** [comment]
this should be fine now in 2.0. [demo](http://js2.coffee/#try:foo%28%29%3B%0A%0A%2F*%0A%20*%20this%20comment%20will%20be%20moved%20up%20with%20foo%28%29%0A%20*%2F%0A%0Afunction%20foo%28%29%20{%0A%20%20%2F%2F%20and%20this%20one%20too%0A%20%20return%20true%3B%0A})
