### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#251]
I've created the try page primary for 
- access to the js2coffwe buils options
- latest ace editor with Line numbers, syntax check, Etc.
- layout changes to display errors

Further
- I found a Designer who could make a new logo
- use a custom build of ace to fix broken backspace bug
- display Version of js2coffee
- replace editor tabs with a switch button (convert from left to right or the other way)

There are still some work to do. For example try to avoid the iframe for the ace editor to make scrolling on touch devices easier.

I think publishing the Website via gh-pages branch is a More flexible solution than via another service like heroku. And there are no extra permission needed for deploying.

So what you think @rstacruz @balupton

**Comment by rstacruz** [comment]
![pasted_image_1_27_15__2_07_pm](https://cloud.githubusercontent.com/assets/74385/5914291/d5e2c13a-a62d-11e4-896d-c07443b5905a.jpg)
