### ISSUE TITLE
Recognize long comments.

### ISSUE THREAD

**Issue by xfix** [js2coffee/js2coffee#257]
If you write code like this:

```javascript
/*
 * Blah blah 2.0
 *
 * Licensed under cake.
 */
```

It's converted to the following.

```coffeescript
#
# * Blah blah 2.0
# *
# * Licensed under cake.
# 
```

My proposal would be convert it to this, which doesn't have needless stars (and is specificially parsed by CoffeeScript 1.7.0 to create nice JavaScript output).

```coffeescript
###
# Blah blah 2.0
#
# Licensed under cake.
###
```

**Comment by rstacruz** [comment]
[fixed in v2.0.0](http://js2coffee.github.io/js2coffee-redux/#try:on%20%3D%203)
