### ISSUE TITLE
convert some coffee keywords into embeded javascript (backticks) and 

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#261]
from [CoffeeScript Lexer Docs](http://coffeescript.org/documentation/docs/lexer.html#section-63) you find these two types of keywords:

```
COFFEE_KEYWORDS = ['undefined', 'then', 'unless', 
                   'until', 'loop', 'of', 'by', 'when']

COFFEE_ALIAS_MAP =
  and  : '&&'
  or   : '||'
  is   : '=='
  isnt : '!='
  not  : '!'
  yes  : 'true'
  no   : 'false'
  on   : 'true'
  off  : 'false'
```

All these keywords should be converted as Embedded JavaScript with backticks.
Here some examples:

```
on.x(y);
on = function() {
  return foobar()
};
```
should be converted into
```
`on`.x y
`on = function() {
  return foobar()
}`
```

So for properties of a keyword can escape the keyword only with backticks.
Direct access like assignments and calls of a keyword should escape the whole expression.

**Comment by rstacruz** [comment]
partially fixed in redux -- [be sure to turn on compatibility mode](http://js2coffee.github.io/js2coffee-redux/#try:on%20%3D%203).
