### ISSUE TITLE
Revert old design

### ISSUE THREAD

**Issue by abuisman** [js2coffee/js2coffee#271]
Hi,

While I love the tool, I don't really like the new design and I find that it doesn't work well.

The design and way of working of the old website were far better.

Alternatively, which is the point in the repository where the change was made? I'd like to host the old site privately in case you won't revert it (which I can imagine as my taste does not have to be shared by others).

**Comment by rstacruz** [comment]
I've been working on a new version of the editor here:

http://js2coffee.github.io/js2coffee-redux/

It comes with most of the new features (like live syntax checks, in-place reverse compiling) and addresses some usability concerns. Try it out and tell me what you think.

**Comment by abuisman** [comment]
Hi @rstacruz 
I don't know if the current design is that new one you spoke of (I assume it is). It looks very awesome. Great work!
It would be very interesting if you could write something up on how you came up with the design and the ideas behind it. That would be a great read :)

**Comment by rstacruz** [comment]
Here are the past versions you can look at:

http://js2coffee.herokuapp.com — 0.1.x
http://v0.js2.coffee — 0.3.x
http://js2.coffee — 2.0 (today)

Actually a blog post might not be a bad idea :)
