### ISSUE TITLE
Wrong property access convertion

### ISSUE THREAD

**Issue by mmavko** [js2coffee/js2coffee#288]
I was converting this snippet in online editor:

```javascript
var concatTarget = ({
  lib: 'js',
  app: 'js',
  templates: 'js',
  libstyles: 'css',
  appstyles: 'css'
})[target];
```

And got this:

```coffeescript
concatTarget = (
  lib: "js"
  app: "js"
  templates: "js"
  libstyles: "css"
  appstyles: "css"
)[{target}]
```

So, there emerges this `{target}`, which compiles back to `{target: target}` which is completely different than original `target`.

Screenshot: http://joxi.ru/oi2PU_3JTJAtYxGM8wU

**Comment by rstacruz** [comment]
[Fixed in redux](http://js2coffee.github.io/js2coffee-redux/#try:var%20concatTarget%20%3D%20%28{%0A%20%20lib%3A%20%27js%27%2C%0A%20%20app%3A%20%27js%27%2C%0A%20%20templates%3A%20%27js%27%2C%0A%20%20libstyles%3A%20%27css%27%2C%0A%20%20appstyles%3A%20%27css%27%0A}%29%5Btarget%5D%3B).
