### ISSUE TITLE
Make anonymous functions more coffee-like

### ISSUE THREAD

**Issue by ldong** [js2coffee/js2coffee#289]
Currently, the following code 
```
(function() {
  return console.log("Hello World");
})();
```

is being determined like 
``` coffeescript
(->
  console.log "Hello World"
)()
```
rather than
```coffeescript
do -> console.log 'Hello World'
```

It would be nice to convert these anonymous functions into `do` statements.

**Comment by rstacruz** [comment]
[I got your back](http://js2coffee.github.io/js2coffee-redux/#try:%28function%20%28document%29%20{%0A%20%20document.dance%28%29%0A}%29%28document%29%3B) ;)

would also love to do `((function ($) {})(jQuery)` into `do ($ = jQuery) ->`, but thats for another day
