### ISSUE TITLE
Error on variables with same name in overlapping scopes

### ISSUE THREAD

**Issue by TrevorBurnham** [js2coffee/js2coffee#3]
It'd be cool if this were a syntax error:

    var foo = bar;
    func = function() {
      var foo = baz;
    }

Something like "Cannot have variables named `foo` in overlapping scopes." The current compilation is, after all, going to yield very different behavior from the original.

**Comment by rstacruz** [comment]
```js
var foo = bar;
func = function() {
  var foo = baz;
}
```

is now a warning in 2.0. [demo](http://js2.coffee/#try:var%20foo%20%3D%20bar%3B%0Avar%20func%20%3D%20function%28%29%20{%0A%20%20var%20foo%20%3D%20baz%3B%0A}).

**Comment by michaelficarra** [comment]
@rstacruz: Couldn't you have compiled to `do (foo = baz) =>`?

**Comment by rstacruz** [comment]
there's still quite a bunch of edge cases to take care of that i'd rather prioritize over niceness :) (also it's not an iife, unless your `do` is a typo)

**Comment by michaelficarra** [comment]
I don't think you're understanding.

```coffee
foo = bar
func = ->
  do (foo = baz) =>
```

would be a faithful compilation that would not require backticks. The only problem is if `arguments` is mentioned within.

**Comment by rstacruz** [comment]
ah, interesting. we went around back and forth trying to find the right workarounds to the scoping problem and never thought of that one!
