### ISSUE TITLE
Be very careful with == undefined

### ISSUE THREAD

**Issue by nickretallack** [js2coffee/js2coffee#301]
I just got a terrible bug due this subtle thing being lost in translation.  I put the file [realtime-client-utils.js](https://developers.google.com/drive/realtime/realtime-quickstart#step_2_set_up_the_sample) through js2coffee.  The place where it gets screwed up is getOption:

``` javascript
rtclient.getOption = function(options, key, defaultValue) {
  var value = options[key] == undefined ? defaultValue : options[key];
  if (value == undefined) {
    console.error(key + ' should be present in the options.');
  }
  console.log(value);
  return value;
}
```

js2coffee converts this to:

``` coffeescript
rtclient.getOption = (options, key, defaultValue) ->
  value = (if options[key] is `undefined` then defaultValue else options[key])
  console.error key + " should be present in the options."  if value is `undefined`
  console.log value
  value
```

And then the coffeescript compiler turns that into:

``` javascript
rtclient.getOption = function(options, key, defaultValue) {
  var value;
  value = (options[key] === undefined ? defaultValue : options[key]);
  if (value === undefined) {
    console.error(key + " should be present in the options.");
  }
  console.log(value);
  return value;
};
```

Note that `==` has become `===`.  Now if you pass in `options` with a `key` whose value is `null`, like it is for several of the options in the example `index.html`, you won't get the default value like you normally would have, since `null !== undefined`.

To fix this problem, I think js2coffee should look for weak comparisons with undefined and output the existential operator `?` instead of the `is` operator.  For example, here's what js2coffee should have generated:

``` coffeescript
rtclient.getOption = (options, key, defaultValue) ->
  value = (if not options[key]? then defaultValue else options[key])
  console.error key + " should be present in the options." if not value?
  console.log value
  value
```

This would compile into:

``` javascript
  rtclient.getOption = function(options, key, defaultValue) {
    var value;
    value = (options[key] == null ? defaultValue : options[key]);
    if (value == null) {
      console.error(key + " should be present in the options.");
    }
    console.log(value);
    return value;
  };
```

...which is functionally equivalent to the original code.

**Comment by timaschew** [comment]
@michaelficarra so why then `undefined` is listed as a coffee keyword?
http://coffeescript.org//documentation/docs/lexer.html#section-67

**Comment by flying-sheep** [comment]
i think the following are most sensible:

1. preserve `... == undefined` as ``(`... == undefined`)`` (wrap in backticks)
2. translate the likely intention, i.e. transform it into the existential operator and emit a warning to stderr.

**Comment by rstacruz** [comment]
In redux, it should keep the old behavior (`a == b` becomes `a == b` just the same), but gives you an error. There would also be a `--compatibility` flag that will translate that to ```a == b``` (with backticks).

**Comment by rstacruz** [comment]
Done. Try it out: [demo](http://js2.coffee/#try:%28function%20camelize%20%28str%29%20{%0A%20%20return%20str.replace%28%2F%5B\s_\-%5D%2B%28%5Ba-zA-Z%5D%29%2Fg%2C%0A%20%20%20%20function%20%28_%2C%20l%29%20{%0A%20%20%20%20%20%20return%20l.toUpperCase%28%29%0A%20%20%20%20}%29%3B%0A}%29%20%3D%3D%20%28function%20alsocamelize%28%29%20{%0A%20%20return%20alert%28true%2C%202%29%3B%0A}%29) (be sure to toggle the "compatibility mode" checkbox to see how it changes)

**Comment by michaelficarra** [comment]
Looks like your demo uncovered a [scoping bug](http://js2.coffee/#try:%28function%20camelize%20%28str%29%20%7B%0A%20%20return%20str.replace%28%2F%5Bs_-%5D%2B%28%5Ba-zA-Z%5D%29%2Fg%2C%0A%20%20%20%20function%20%28_%2C%20l%29%20%7B%0A%20%20%20%20%20%20return%20l.toUpperCase%28%29%0A%20%20%20%20%7D%29%3B%0A%7D%29%20%3D%3D%20%28function%20alsocamelize%28%29%20%7B%0A%20%20return%20alert%28true%2C%202%29%3B%0A%7D%29).

**Comment by rstacruz** [comment]
what sort of scoping bug?

**Comment by michaelficarra** [comment]
Oh, the link didn't copy right. I was trying to show that function expression names are leaking outside their function name scope in the compiled output.

**Comment by rstacruz** [comment]
ah, you'll have to click the "link" button below (or ctrl+k), much like [coffeescript.org](http://coffeescript.org/#try:a)'s implementation :)

**Comment by michaelficarra** [comment]
http://js2.coffee/#try:(function%20f()%20%7B%7D)%0Atypeof%20f%3B

**Comment by rstacruz** [comment]
aw man, mea culpa. i actually thought that's the behavior of named function expressions, even if they're not function declarations

**Comment by michaelficarra** [comment]
Nope. They create an independent scope that contains just their name. It is not leaked outside the FE.
