### ISSUE TITLE
rewrite of js2coffee

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#312]
this is related to https://github.com/js2coffee/js2coffee/issues/270

since js2coffee using narcissus for parsing the JS AST and narcissus is not just buggy, it's really old and deprecated. So it would be nice to use esprima, acorn or the uglify parser which is not an implementation of [Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) but can be transformed into it, therefor it has some more nice features.

@michaelficarra 
And maybe it would make more sense to write it new instead of refactor it. And in that case maybe support coffee-redux. I'm not into it, just fly over the __Intentional Deviations__ and not sure how big the diff is and if it's possible to support both coffee and coffee-redux.

What you think?

**Comment by rstacruz** [comment]
Posted some updates: #333

At the moment it should be pretty solid. I'm confident about the idea of replacing `js2coffee 0.x` eventually with the rewrite, as soon as some more polishing is added in, and the site fully updated.

http://js2coffee.github.io/js2coffee-redux/
