### ISSUE TITLE
Logging of `true`

### ISSUE THREAD

**Issue by aramk** [js2coffee/js2coffee#315]
For some reason I'm getting a "true" printed out from the code below:

```
js2coffee.build(scriptStr, {indent: '  ', single_quotes: true})
```

This is usually harmless, but for a script that generates output it means I've had to hack into `console.log` to prevent this appearing in the output.

**Comment by jysperm** [comment]
https://github.com/js2coffee/js2coffee/blob/master/src/documents/lib/js2coffee.js.coffee#L41

    if opts.single_quotes? and opts.single_quotes is true
      console.log opts.single_quotes
      strEscape = strEscapeSingleQuotes
    else
      strEscape = strEscapeDoubleQuotes
