### ISSUE TITLE
"for" and "if" after

### ISSUE THREAD

**Issue by dalph** [js2coffee/js2coffee#316]
if I write a if after for without {, then converter write wrong.
Easy example:

for (i in []) if (i) {
    i++;
}

make:

for i of []
  continue

**Comment by rstacruz** [comment]
The new version takes care of this: [demo](http://js2coffee.github.io/js2coffee-redux/#try:for%20%28var%20k%20in%20%28c%20%3D%20components%28graph%2C%20key%29%29%29%0A%20%20if%20%28%28m%20%3D%20maxAreas%5Bk%5D%29%20%3E%20max%29%20max%20%3D%20m%3B%0A)

**Comment by rstacruz** [comment]
and OP's case of for..in: [demo](http://js2coffee.github.io/js2coffee-redux/#try:for%20%28var%20i%20in%20%5B%5D%29%20if%20%28i%29%20{%0Ai%2B%2B%3B%0A})

**Comment by dalph** [comment]
Thx very much

воскресенье, 25 января 2015 г. пользователь Rico Sta. Cruz написал:
