### ISSUE TITLE
Web: scrolling

### ISSUE THREAD

**Issue by xixixao** [js2coffee/js2coffee#317]
The Ace kitchensink works fine, but the editor on the j2coffee website scrolls too fast, on a Mac, FF 31.

**Comment by rstacruz** [comment]
The new version ([js2coffee-redux](https://github.com/js2coffee/js2coffee-redux/), [demo here](http://js2coffee.github.io/js2coffee-redux/)) now uses CodeMirror instead of Ace. It should be much more pleasant to use, too. Try it out and see if you encounter any issues.

**Comment by xixixao** [comment]
Snazzy, nice. Mind sharing why you went with CodeMirror instead of Ace?

**Comment by rstacruz** [comment]
Mostly I just felt Ace was too... kitchen-sink-like. I know it can be customized to be less overbearing, but mostly it was just gut feel that codemirror would be a better fit.
