### ISSUE TITLE
Empty case+break falls thru to next case bug

### ISSUE THREAD

**Issue by pronebird** [js2coffee/js2coffee#319]
Hi,

The following switch case scenario:

```js
for(var i = 0; i < 10; i++) {
    switch(i) {
        case 1:
            break;
        case 2:
            alert('2')
            break;
    }
}
```

becomes:

```coffee
while i < 10
  switch i
    when 1, 2
      alert "2"
  i++
```

First case should not fall thru. Should be simply omitted.

**Comment by rstacruz** [comment]
Fixed in the upcoming js2coffee 2.0 (js2coffee-redux). [Demo](http://js2coffee.github.io/js2coffee-redux/#try:switch%28i%29%20{%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20%20%20alert%28%272%27%29%0A%20%20%20%20%20%20%20%20break%3B%0A})
