### ISSUE TITLE
Feature request: sharing code

### ISSUE THREAD

**Issue by lolmaus** [js2coffee/js2coffee#329]
Hi!

I love CoffeeScript. In order to refine my code, i need a tool that does several useful things.

Unfortunately, there's no tool that does everything i need. I have to constantly switch between three different tools:

***

| Feature             | CoffeeScript.org            | js2coffee.org             | jsbin.com                 |
| --------------------|:---------------------------:|:-------------------------:|:-------------------------:|
| Syntax highlighting | :broken_heart:              | :green_heart:             | :green_heart:             |
| Error highlighting  | :broken_heart:<sup>1</sup>  | :green_heart:<sup>2</sup> | :yellow_heart:<sup>3</sup>|
| Code execution      | :green_heart:               | :green_heart:<sup>4</sup> | :green_heart:             |
| JS code display     | :green_heart:               | :green_heart:             | :broken_heart:            |
| Reverse compilation | :broken_heart:              | :green_heart:             | :broken_heart:            |
| Sharing code        | :yellow_heart:<sup>5</sup>  | :broken_heart:            | :green_heart:             |
| Score (out of 6)    | **2.5**                       | **5**                     | **3.5**                   |

1. Reports error's line number whereas lines aren't visually numbered.
2. Displays the error next to the erroneous line.
3. Reports error's line number, have to manually enable line numbers and find the line in question.
4. Hidden feature: press Ctrl+Enter in the JS tab.
5. Does not store the code. Rather, embeds the code into the URL.

***

js2coffee is my favorite tool. Among the three services, i wish js2coffee were the one to have the complete functionality.

Currently it lacks only code sharing.

Code sharing can be easily implemented via gist.github.com. You can store snippets from both anonymous and Github-authorized users.

**Comment by rstacruz** [comment]
I never really liked how reverse compile works right now... lets see if we can do some UX improvements on that on the next version.

**Comment by rstacruz** [comment]
I've implemented a [what i think is] better UX for reverse compilation to the new editor. no more confusing "Which pane am I editing again?" moments!

http://js2coffee.github.io/js2coffee-redux/

Won't explain how to use it (i'm hoping it'd be obvious) — @lolmaus try it out. Would love to get sharing working some time soon too.

**Comment by pronebird** [comment]
Would be great to style scrollbars.

![image](https://cloud.githubusercontent.com/assets/704044/5888417/3e5d801a-a3fe-11e4-9ce2-5c86e40149a7.png)

**Comment by pronebird** [comment]
Reverse compiler won't work the same because we adapt JS to Coffee when necessary plus optimize loops, etc..

**Comment by rstacruz** [comment]
Scrollbars are better now :)

**Comment by rstacruz** [comment]
Sharing and code execution are also available on the new editor now!
