### ISSUE TITLE
anitpattern preinstall script

### ISSUE THREAD

**Issue by cameronjroe** [js2coffee/js2coffee#330]
I'm having some trouble installing the package. It's failing on the preinstall with ./cyclic.js because it can't be found. I also found that npm is discouraging the use of preinstall scripts:
https://docs.npmjs.com/misc/scripts#note-install-scripts-are-an-antipattern

I'd like to update another repo to 0.3.5 but npm won't run the update because of this. Any ideas?

**Comment by rstacruz** [comment]
We've been trying to address the bloat of the repo in general. The new version ([js2coffee-redux](https://github.com/js2coffee/js2coffee-redux/), [demo here](http://js2coffee.github.io/js2coffee-redux/)) should solve these concerns. try it out using `npm install [-g] js2coffee-redux`, then `js2c --help`.
