### ISSUE TITLE
Error feedback doesn't show in Firefox

### ISSUE THREAD

**Issue by RoelN** [js2coffee/js2coffee#332]
In the [online js2coffee converter](http://js2coffee.org/) error messages aren't shown in the speech bubble at the top right of the page. This occurs with any error in Firefox 34.0.5 on Mac OS X Yosemite. Latest Chrome and Opera work fine.

The error message simply isn't inserted into `div.infobox-content`.

**Comment by rstacruz** [comment]
Errors are now available inline (see the left gutter of the code editor).

Also, have a look at the new version as well: https://github.com/js2coffee/js2coffee-redux/

**Comment by RoelN** [comment]
Yeah, those js2coffee errors don't show up indeed. But the redux looks awesome. Kudos!
