### ISSUE TITLE
Redux updates

### ISSUE THREAD

**Issue by rstacruz** [js2coffee/js2coffee#333]
Hi everyone,

The [js2coffee-redux](https://github.com/js2coffee/js2coffee-redux/) rewrite has been going pretty well. It's mostly at a point that it achieves close to parity with the current version. Eventually, it will replace the current js2coffee version.

Try it out here:

**http://js2coffee.github.io/js2coffee-redux/**

This new rewrite features a whole new parser ([Esprima](http://esprima.org)), which means it's much more future-proof and will be able to support ES6 and such. Here's a rundown of the *new* features:

- Esprima parser
- Cleaner repo (the site is decoupled from the library itself!)
- Less boilerplate (no docpad, cyclic.js, etc)
- Warnings (try it with `a == b`)
- Better errors (try it with `off = 2`)
- AST mode (`js2c file.js --ast`), which prints the CoffeeScript AST

If you're having trouble with the current version, do give [js2coffee-redux](https://github.com/js2coffee/js2coffee-redux/) a try.

cc @timaschew @balupton

**Comment by pronebird** [comment]
We'll have to fix continue in loops once again :-)

**Comment by timaschew** [comment]
>We'll have to fix continue in loops once again :-) 

:stuck_out_tongue_closed_eyes: 

but it looks very nice, I like it, awesome @rstacruz

**Comment by pronebird** [comment]
It looks awesome and online editor is so much better!

@rstacruz tremendous work!

**Comment by flying-sheep** [comment]
> We'll have to fix continue in loops once again :-)

ahahaha, i literally had this issue opened in another tab while checking if this was the case lol

**Comment by pronebird** [comment]
LOL. I just hope that with Esprima we could find a better/cleaner way to apply micro-patches like a continue case in while loops.

**Comment by pronebird** [comment]
We can't really get over this issue. Btw, wouldn't it make more sense to open this issue in redux repo? Redux is not merged to main repo and is still kind of beta right?

**Comment by timaschew** [comment]
:+1:  https://github.com/js2coffee/js2coffee/issues/49#issuecomment-71313274

**Comment by flying-sheep** [comment]
oh, as per [this comment](https://github.com/js2coffee/js2coffee/issues/312#issuecomment-71311298) i understood that the merge would be very soon, so i already created the label and reopened #49…

if that’s wrong, please feel free to revert it, but we could also dogfood with redux…

**Comment by timaschew** [comment]
> replacing

not merging. As Rico said, it's a rewrite otherwise he had created a branch or something like that

**Comment by pronebird** [comment]
You don't plan to abandon this repo don't you?

**Comment by flying-sheep** [comment]
i was just typing the same question when your comment popped up:

will this repo be abandoned and ´npm instally js2coffee` will install redux at some point in the future?

that’ll confuse newcomers

**Comment by rstacruz** [comment]
yes. `continue` — on my radar :)

**Comment by rstacruz** [comment]
> LOL. I just hope that with Esprima we could find a better/cleaner way to apply micro-patches like a continue case in while loops.

It seems like it'd mostly be implemented in the same manner: when encountering `continue`, see if it's inside a `for` loop with an update, then inject the update just before it.

One difference though: js2coffee-redux operates by transforming a JS ast to a Coffee ast (just at it probably should have in the beginning). in js2coffee 0.x, it was implemented in the step that 'stringifies' the AST.

**Comment by rstacruz** [comment]
@flying-sheep :+1:

**Comment by rstacruz** [comment]
Alright, I'm going to tentatively schedule the redux rollover for **February 2, 2015**. Please let me know if there are any issues on this.

As of today, redux passes most of legacy's tests, while others fail mostly because of stylistic considerations (braces, postfix if's, X:: vs X.prototype, etc). You can check this out by doing `ALL=1 npm test` in redux.

The move will happen as:

- move the current `master` branch to `v0.x`.
- move the current `gh-pages` branch to `v0.x/gh-pages`.
- move the js2coffee-redux's master branch to js2coffee's `master`.
- move the js2coffee-redux's gh-pages branch to js2coffee's `gh-pages`.
- publish the new version as `v2.0.0`. (let's skip 1.0 because lets face it, js2coffee has been like a v1.x the whole time anyway)

Furthermore:

- We'll move to a new domain: `js2.coffee`. The old domain (`js2coffee.org`) will redirect to it.
- We'll get the legacy version instated in `legacy.js2.coffee` for archiving.
- `http://js2coffee.github.io/js2coffee-redux` will be a redirect to `js2.coffee`.
- the redux repo will be emptied out, save for a README.md that will point to the current repo.

**Comment by flying-sheep** [comment]
:fireworks:

**Comment by balupton** [comment]
Great!

**Comment by rstacruz** [comment]
2.0.0 is out :)

**Comment by timaschew** [comment]
@rstacruz great work, but why you deleted/overwritten the complete git history of the old js2coffee source code? you did a `git push --force`?

**Comment by timaschew** [comment]
// edit
sorry didn't see the branch ^^

**Comment by pronebird** [comment]
:beers:
