### ISSUE TITLE
Very minor spelling error

### ISSUE THREAD

**Issue by Ranhiru** [js2coffee/js2coffee#334]
The **Try out in the browser** section spells switch incorrectly.

js2coffee.org
You can ~~swtich~~ switch the mode (JS -> Coffee and Coffee -> JS) at the top in the center.

I could send a pull request if you want to but I don't think such a minor issue warrants one.

**Comment by rstacruz** [comment]
thanks! actually that text is pretty much outdated now because somehow that switch was removed. anyway, we'll be migrating to a whole new editor soon (#333)
