### ISSUE TITLE
Make parentheses, square brackets, and curly braces match with their corresponding type. 

### ISSUE THREAD

**Issue by tombert** [js2coffee/js2coffee#344]
I love the new update to the js2.coffee site, but I'm a little frustrated by the fact that in the update, the feature of matching braces and parentheses was removed. Is there any way to add that back?

**Comment by rstacruz** [comment]
like this http://codemirror.net/demo/closebrackets.html ? yeah, we can do that.

**Comment by tombert** [comment]
It's not showing the matching braces in the link you sent me, though I know CodeMirror supports it (as that's what LightTable uses).

**Comment by rstacruz** [comment]
easy enough... try it out :)

**Comment by tombert** [comment]
You are awesome! Thank you for making this awesome tool even more awesome!
