### ISSUE TITLE
Nested ternary Operator doesn't compile proper   

### ISSUE THREAD

**Issue by aokolovskis** [js2coffee/js2coffee#345]
JS:

    str += String.fromCharCode(r+=r>9?r<36?55:61:48);

js2coffeeV2:

    str += String.fromCharCode(r += if r > 9 then if r < 36 then 55 else 61 else 48)

js2coffee old:

    String.fromCharCode r += (if r > 9 then (if r < 36 then 55 else 61) else 48)

Adding parentheses to the javascript code doesn't solve the problem as well. 
The new js2coffee coffee code doesn't compile anymore (unexpected else).

kind regards

**Comment by rstacruz** [comment]
Try it now, 2.0.1 is out and fixes this.

**Comment by aokolovskis** [comment]
Thanks
