### ISSUE TITLE
Almacenar archivos

### ISSUE THREAD

**Issue by jonorozcoc** [js2coffee/js2coffee#350]
Solo muestra la salida del Coffeescript en la consola, no permite guardar esa información en un archivo.

**Comment by rstacruz** [comment]
sorry buddy, I don't speak spanish here—did you mean to request for a feature to save the output to a file from the js2.coffee website?

**Comment by pronebird** [comment]
I guess he meant that js2coffee simply outputs everything to console.

This should work for you:
`js2coffee input.js > output.coffee`

**Comment by jonorozcoc** [comment]
Ok.
