### ISSUE TITLE
Missing dependency "coffee-script"

### ISSUE THREAD

**Issue by creynders** [js2coffee/js2coffee#351]
I think you should move "coffee-script" from devDependencies to dependencies, since `index.js` uses it.

**Comment by rstacruz** [comment]
Indeed

**Comment by rstacruz** [comment]
v2.0.2 now fixes this, thanks for the report!

**Comment by rstacruz** [comment]
On second thought, this is not necessary at all—I've wired the package to just use the pre-built `js2coffee.js`, no need for `coffee-script` as a dependency. Besides, using `coffee-script/register` in a library is considered bad practice anyway.

**Comment by creynders** [comment]
Thanks, works like a charm!
