### ISSUE TITLE
Forced to default browsers instead container

### ISSUE THREAD

**Issue by noma4i** [js2coffee/js2coffee#352]
Iv used Fluid for a long time to make the app from this tool. However that now is forcing to open in default browser(safari for me). 

This issue is about js2.coffee website.

**Comment by rstacruz** [comment]
Can you (on anyone) help debug the issue? I'm not a user of Fluid here and I don't know what can possibly cause it.

**Comment by noma4i** [comment]
Iv spent some time to dig this issue. Looks like Fluid app issue.

**Comment by barryceelen** [comment]
For future reference: Had the same issue. Somehow Fluid ended up setting *js2coffee.org* in its "Whitelist Preferences" in stead of *js2.coffee*.

![pasted_image_02_09_15_18_13](https://cloud.githubusercontent.com/assets/4179791/9637024/c1562eb0-519e-11e5-84a7-eff22faf5bbf.png)
