### ISSUE TITLE
Syntax theme name

### ISSUE THREAD

**Issue by PabloVallejo** [js2coffee/js2coffee#361]
Syntax highlight styles are really great, is that theme available for Sublime Text or Atom?

![js2coffee_2_0_ _convert_javascript_to_coffeescript](https://cloud.githubusercontent.com/assets/1751074/6584779/ae75aade-c73b-11e4-9119-cb4f73d18732.png)

Thanks,

**Comment by flying-sheep** [comment]
[this file](http://js2.coffee/assets/vendor.css) says it’s a CodeMirror theme called “ambiance”

**Comment by PabloVallejo** [comment]
Thanks a lot!

**Comment by flying-sheep** [comment]
no problem :)

**Comment by rgnevashev** [comment]
did you found a way how to put the theme to sublime 3? I did not find the final theme "ambiance" ....

**Comment by rstacruz** [comment]
Indeed it is ambiance. Sorry I can't point you to a sublime theme.

https://github.com/js2coffee/js2coffee/blob/gh-pages/Makefile#L22
https://github.com/codemirror/CodeMirror/blob/master/theme/ambiance.css

**Comment by rgnevashev** [comment]
it would be cool to convert css file to sublime tmTheme file... thx for links :)
