### ISSUE TITLE
bug with round brackets

### ISSUE THREAD

**Issue by alexey-shaposhnikov** [js2coffee/js2coffee#373]
my javascript:
```
var length = data.length - (positionOne + someOne); // example 96 - (34 + 32) = 30
```

converted coffeescript:
```
 length = data.length - positionOne + someOne
```

**Comment by alexey-sh** [comment]
anybody here?

**Comment by rstacruz** [comment]
hey there! I'm here, but I'm a bit preoccupied to be making patches at the moment.

the `a - (b - c)` is handled correctly, but the `a - (b + c)` isn't — PR's are welcome!

**Comment by rstacruz** [comment]
Okay, v2.0.4 is out to fix this. http://js2.coffee

**Comment by alexey-shaposhnikov** [comment]
@rstacruz Thank you so much!
