### ISSUE TITLE
/** convertin to ###*

### ISSUE THREAD

**Issue by mrapogee** [js2coffee/js2coffee#375]
While technically correct, no one wants that extra * there.

**Comment by michaelficarra** [comment]
No, they do.

**Comment by mrapogee** [comment]
Really? It's just from comments like

```
/**
 * blah
 **/
```
Is there something I'm missing? Are they for a purpose?

**Comment by rstacruz** [comment]
Yes, because it allows you to make jsdoc comments in coffeescript.

```coffee
###*
# gets the circumference of a circle
# @param r radius
###
getCircumference: (r) ->
  Math.PI * r * 2
```

**Comment by mrapogee** [comment]
I didn't realize this was the syntax for coffescript docs.
