### ISSUE TITLE
object colon error

### ISSUE THREAD

**Issue by codepawn** [js2coffee/js2coffee#377]
```
a =
  "b": 1
  "e": 2
```
  
there is an error that 'unexpacted :'
but when you put one more tab in the b

```
a =
		"b": 1
  "e": 2
```
  
this is work well

**Comment by rstacruz** [comment]
neither of those are valid javascript. can you go to http://js2.coffee/, type your code in, then click "Link" and paste the URL here?

**Comment by codepawn** [comment]
Okay it's 

http://js2.coffee/#coffee/try:a%20%3D%0A%09%22b%22%3A%201%0A%20%20%22e%22%3A%202%0A%20%20

**Comment by rstacruz** [comment]
ah, that would be a coffeescript issue then, not js2coffee.

the reason you're getting an error is that line 2 has a tab, but line 3 has 2 spaces. [This one](http://js2.coffee/#coffee/try:a%20%3D%0A%20%20%22b%22%3A%201%0A%20%20%22e%22%3A%202%0A) works.

**Comment by codepawn** [comment]
Thank you for the fast answer :)
