### ISSUE TITLE
== between string and number

### ISSUE THREAD

**Issue by bormat** [js2coffee/js2coffee#381]
Good morning
When we convert equality  like a == 2 if a is equal to 2 in js it work but because of the transformation into  === it doesn't work.
a good solution would be to translate a == 2 into +a===2
I know it is my fault because I compare string wih number but it is easier to correct it when we see the "+"
an other little bug but not important is  when you use comma in while loop,it don't understand
thanks

**Comment by rstacruz** [comment]
Turn on compatibility mode. Thats `jscoffee --compat` (in the CLI) or the sidebar checkbox is the online site (http://js2.coffee).
