### ISSUE TITLE
Incorrect converted '==='

### ISSUE THREAD

**Issue by hbakhtiyor** [js2coffee/js2coffee#384]
Instead to convert to 'is', the converter converted to '=='

**Comment by flying-sheep** [comment]
coffeescript `==` is a synonym to `is`, just like `!=` equals `isnt`. `==`/`is` compiles to JS `===` and `!=`/`isnt` compiles to JS `!==`.

so it’s a stylistic choice if JS `===` should be converted to `==` or `is`.
