### ISSUE TITLE
Does your website send our code to your server ?

### ISSUE THREAD

**Issue by Aewil** [js2coffee/js2coffee#420]
Hi all !

I think all about is in the title ;)

Regards,

Aewil

**Comment by rstacruz** [comment]
Nope!

https://github.com/js2coffee/js2coffee/tree/gh-pages
https://github.com/js2coffee/js2coffee/blob/gh-pages/assets/app.js

**Comment by Aewil** [comment]
Quick answer, thanks you ! And fpr ur great app too ;)
