### ISSUE TITLE
JS2Coffee Site Is Broken

### ISSUE THREAD

**Issue by turnerniles** [js2coffee/js2coffee#433]
Site errors on load.

![image](https://cloud.githubusercontent.com/assets/8146241/14066280/570260de-f413-11e5-9746-3156af29dc78.png)

Javascript Console Error
Failed to load resource: the server responded with a status of 404 (Not Found)
https://a248.e.akamai.net/assets.github.com/img/e6bef7a091f5f3138b8cd40bc3e…622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67

**Comment by balupton** [comment]
Is it working for you now? Perhaps akamai had some downtime. As working fine for me.

**Comment by rstacruz** [comment]
works now. indeed looks like a CDN hiccup. thanks for the report!
