### ISSUE TITLE
website doesnt seem to work, neither the npm installation script

### ISSUE THREAD

**Issue by Oglomuntonido** [js2coffee/js2coffee#464]
http://js2coffee.thomaskalka.de 
th right window shows only ReferenceError: Can't find variable: SCRIPT

trying to install via $ npm install js2coffee on macos

after that using command js2coffee returns command not found

**Comment by rstacruz** [comment]
That's not the website,  try http://js2.coffee :)

**Comment by rstacruz** [comment]
Also,  it should be npm install -g js2coffee

**Comment by Oglomuntonido** [comment]
Was using both websites, mostly preferred output of the http://js2coffee.thomaskalka.de
different compile settings perhaps?

Many thanks
M
