### ISSUE TITLE
`continue`s in for loops don't execute the update step statement

### ISSUE THREAD

**Issue by rstacruz** [js2coffee/js2coffee#49]
``` javascript
for (i = 0; i < 30; ++i) {
  if (true) continue;
}
```

Gets compiled to:

```coffeescript
i = 0
while i < 30
  continue if true
  ++i
```

...which erroneously skips the `++i`.

**Comment by flying-sheep** [comment]
reopened for redux

**Comment by timaschew** [comment]
I would prefer to leave this issue closed and create a new issue in the redux repository and link to this issue here

**Comment by pronebird** [comment]
I moved this issue to https://github.com/js2coffee/js2coffee-redux/issues/4

**Comment by rstacruz** [comment]
Found some cases that js2coffee 0.x chokes on:

![pasted_image_1_25_15__4_12_pm](https://cloud.githubusercontent.com/assets/74385/5890869/0652ebce-a4ad-11e4-8dc1-8711a7389cfd.png)

Fixed in redux: [demo](http://js2coffee.github.io/js2coffee-redux/#try:for%28%3B%20%3B%20el.outerWidth%29%20{%0A%20%20if%20%28x%29%20continue%3B%0A%20%20continue%3B%0A})
