### ISSUE TITLE
Func(@variable) ->

### ISSUE THREAD

**Issue by Qard** [js2coffee/js2coffee#74]
Currently this;

    var Func = function(variable){
      this.variable = variable
    }

Translates to this;

    Func = (variable) ->
      @variable = variable

Optimally, it should translate to this;

    Func = (@variable) ->

Not sure what the challenges are to that implementation, but just thought I'd mention it. It seems to be a similar issue to this; https://github.com/rstacruz/js2coffee/issues/22

**Comment by rstacruz** [comment]
Closing this now because as of CoffeeScript 1.9, `fn = (@x) ->` does not translate to `function (x) { this.x = x; }` anymore. `x` will not be available in the scope, only `this.x` is.
