### ISSUE TITLE
Failed to convert ternary if (?) followed by object with more than 1 property ({a:b,c:d})

### ISSUE THREAD

**Issue by steerapi** [js2coffee/js2coffee#77]
#js source:

a = (b ? {c:d,e:f} : g)

#js2coffee:

a = (if b then 
  c: d
  e: f
 else g)

#coffee -c:

Error: Parse error on line 3: Unexpected 'THEN

#expected js2coffee result:

a = (if b then (
  c: d
  e: f )
 else g)

**Comment by rstacruz** [comment]
works now in 2.0
